#!/bin/bash

mkdir -p "$HOME/.var/app/org.chromium.Chromium/config"
cat > "$HOME/.var/app/org.chromium.Chromium/config/chromium-flags.conf" << EOF
--force-dark-mode
--enable-features=WebUIDarkMode
--ozone-platform-hint=auto
EOF
