#!/bin/sh

if [ ! -f "$HOME/.config/zsh/init.zsh" ]; then
  command mkdir -p "$HOME/.config/zsh"
  command git clone "https://github.com/notfirefox/init.zsh.git" "$HOME/.config/zsh"
  command git -C "$HOME/.config/zsh" submodule update --init --recursive
fi
echo "source $HOME/.config/zsh/init.zsh" > "$HOME/.zshrc"
