#!/bin/bash

CONFIG_DIR="$HOME/.var/app/org.chromium.Chromium/config"

mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_DIR/chromium-flags.conf" << EOF
--force-dark-mode
--enable-features=WebUIDarkMode
--ozone-platform-hint=auto
EOF
