#!/bin/sh

configure_chromium() {
  CONFIG_DIR="$HOME/.var/app/org.chromium.Chromium/config"

  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_DIR/chromium-flags.conf" << EOF
--force-dark-mode
--enable-features=WebUIDarkMode
--ozone-platform-hint=auto
EOF
}

setup_flatpak() {
  FLATHUB_URL="https://flathub.org/repo/flathub.flatpakrepo"

  flatpak remote-add --if-not-exists flathub "$FLATHUB_URL"
  flatpak install org.kde.ark \
                  org.chromium.Chromium \
                  org.kde.elisa \
                  org.kde.gwenview \
                  org.kde.kid3 \
                  org.kde.kile \
                  org.kde.kwrite \
                  org.kde.kontact \
                  org.kde.okular \
                  io.mpv.Mpv
  flatpak override --user --socket=pcsc org.chromium.Chromium
  flatpak override --user --env=QT_QPA_PLATFORM=wayland org.kde.kontact
  flatpak override --user --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
}

setup_nvim() {
  NVIM_DIR="$HOME/.config/nvim"
  NVIM_GIT="https://github.com/notfirefox/init.lua.git"

  if [ ! -f "$NVIM_DIR/init.lua" ]; then
    mkdir -p "$NVIM_DIR"
    git clone "$NVIM_GIT" "$NVIM_DIR"
  fi
}

setup_zsh() {
  ZSH_DIR="$HOME/.config/zsh"
  ZSH_GIT="https://github.com/notfirefox/init.zsh.git" 

  if [ ! -f "$ZSH_DIR/init.zsh" ]; then
    mkdir -p "$ZSH_DIR"
    git clone "$ZSH_GIT" "$ZSH_DIR"
    git -C "$ZSH_DIR" submodule update --init --recursive
  fi

  echo "source $ZSH_DIR/init.zsh" > "$HOME/.zshrc"
}

configure_chromium
setup_flatpak
setup_nvim
setup_zsh
